"""init users and issues

Revision ID: 801bc0b6d2d6
Revises: 
Create Date: 2026-03-19 06:00:42.768750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801bc0b6d2d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'moderator', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('pending_ai', 'approved', 'rejected', 'in_progress', 'resolved', name='issuestatus'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='ck_issues_priority_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_user_id'), 'issues', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_user_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # PostgreSQL: enum types are not removed with the tables
    op.execute(sa.text("DROP TYPE IF EXISTS issuestatus"))
    op.execute(sa.text("DROP TYPE IF EXISTS userrole"))
    # ### end Alembic commands ###
